package storage

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

// R2Config holds all configuration required to connect to Cloudflare R2.
// All fields are sourced from environment variables — never hardcoded.
type R2Config struct {
	// Endpoint is the R2 S3-compatible endpoint:
	// https://<account-id>.r2.cloudflarestorage.com
	Endpoint string

	// BucketName is the name of the R2 bucket.
	BucketName string

	// AccessKeyID and SecretAccessKey are R2 API token credentials
	// (generated in Cloudflare Dashboard → R2 → Manage R2 API Tokens).
	// These are NOT AWS IAM credentials.
	AccessKeyID     string
	SecretAccessKey string

	// PublicURL is the Cloudflare CDN custom domain configured for the bucket,
	// e.g. "https://assets.tudominio.com". Used only for public objects.
	PublicURL string
}

// R2Client implements StorageClient for Cloudflare R2.
// Internally it uses the AWS SDK v2 pointing to R2's S3-compatible endpoint.
type R2Client struct {
	s3Client      *s3.Client
	presignClient *s3.PresignClient
	cfg           R2Config
}

// NewR2Client creates a new R2Client from the given configuration.
// It validates connectivity is possible (credentials present) but does NOT
// make a network call on startup.
func NewR2Client(cfg R2Config) (*R2Client, error) {
	if cfg.Endpoint == "" || cfg.BucketName == "" {
		return nil, fmt.Errorf("storage: R2Config is incomplete — Endpoint and BucketName are required")
	}

	opts := []func(*awsconfig.LoadOptions) error{
		awsconfig.WithRegion("auto"),
	}

	// Use static credentials if provided; otherwise let the SDK resolve from the default chain.
	if cfg.AccessKeyID != "" && cfg.SecretAccessKey != "" {
		opts = append(opts, awsconfig.WithCredentialsProvider(
			credentials.NewStaticCredentialsProvider(cfg.AccessKeyID, cfg.SecretAccessKey, ""),
		))
	}

	// R2 requires region "auto" and path-style URLs.
	awsCfg, err := awsconfig.LoadDefaultConfig(context.Background(), opts...)
	if err != nil {
		return nil, fmt.Errorf("storage: failed to build AWS config for R2: %w", err)
	}

	s3Client := s3.NewFromConfig(awsCfg, func(o *s3.Options) {
		o.BaseEndpoint = aws.String(cfg.Endpoint)
		// R2 does not support virtual-hosted style (bucket.endpoint).
		// Path style (endpoint/bucket) is required.
		o.UsePathStyle = true
	})

	return &R2Client{
		s3Client:      s3Client,
		presignClient: s3.NewPresignClient(s3Client),
		cfg:           cfg,
	}, nil
}

// PutObject uploads data directly to R2. This is the primary upload path:
// the Lambda receives the file bytes from the client and forwards them here.
func (c *R2Client) PutObject(ctx context.Context, key string, data []byte, contentType string) error {
	_, err := c.s3Client.PutObject(ctx, &s3.PutObjectInput{
		Bucket:        aws.String(c.cfg.BucketName),
		Key:           aws.String(key),
		Body:          bytes.NewReader(data),
		ContentType:   aws.String(contentType),
		ContentLength: aws.Int64(int64(len(data))),
	})
	if err != nil {
		return fmt.Errorf("storage: PutObject(%q): %w", key, err)
	}
	return nil
}

// DeleteObject removes an object from R2.
// Called during rollback when a concurrent batch upload partially fails.
func (c *R2Client) DeleteObject(ctx context.Context, key string) error {
	_, err := c.s3Client.DeleteObject(ctx, &s3.DeleteObjectInput{
		Bucket: aws.String(c.cfg.BucketName),
		Key:    aws.String(key),
	})
	if err != nil {
		return fmt.Errorf("storage: DeleteObject(%q): %w", key, err)
	}
	return nil
}

// ObjectExists checks whether an object exists in R2 and returns its size in bytes.
func (c *R2Client) ObjectExists(ctx context.Context, key string) (bool, int64, error) {
	out, err := c.s3Client.HeadObject(ctx, &s3.HeadObjectInput{
		Bucket: aws.String(c.cfg.BucketName),
		Key:    aws.String(key),
	})
	if err != nil {
		// HeadObject returns a generic error for 404 — treat as "not found"
		return false, 0, nil
	}
	return true, aws.ToInt64(out.ContentLength), nil
}

// PublicURL returns the Cloudflare CDN URL for a public object.
// No expiry — Cloudflare CDN handles caching automatically.
func (c *R2Client) PublicURL(key string) string {
	base := strings.TrimRight(c.cfg.PublicURL, "/")
	return fmt.Sprintf("%s/%s", base, key)
}

// GenerateGetURL produces a time-limited presigned GET URL for a private object.
// The URL is generated by the Lambda on demand and returned to the client;
// it is never stored in the database.
func (c *R2Client) GenerateGetURL(ctx context.Context, key string, ttl time.Duration) (string, error) {
	req, err := c.presignClient.PresignGetObject(ctx,
		&s3.GetObjectInput{
			Bucket: aws.String(c.cfg.BucketName),
			Key:    aws.String(key),
		},
		s3.WithPresignExpires(ttl),
	)
	if err != nil {
		return "", fmt.Errorf("storage: GenerateGetURL(%q): %w", key, err)
	}
	return req.URL, nil
}

// DetectContentType downloads the first 512 bytes of an object and uses
// Go's standard library magic-number detection to return its real MIME type.
// This prevents MIME spoofing (e.g. a .exe renamed as .jpg).
func (c *R2Client) DetectContentType(ctx context.Context, key string) (string, error) {
	out, err := c.s3Client.GetObject(ctx, &s3.GetObjectInput{
		Bucket: aws.String(c.cfg.BucketName),
		Key:    aws.String(key),
		Range:  aws.String("bytes=0-511"),
	})
	if err != nil {
		return "", fmt.Errorf("storage: DetectContentType(%q): %w", key, err)
	}
	defer out.Body.Close()

	header := make([]byte, 512)
	n, err := io.ReadFull(out.Body, header)
	if err != nil && err != io.ErrUnexpectedEOF {
		return "", fmt.Errorf("storage: DetectContentType(%q) read: %w", key, err)
	}

	return http.DetectContentType(header[:n]), nil
}

