package model

import "time"

// AssetStatus represents the lifecycle state of a stored asset.
type AssetStatus string

// AssetEntityType identifies what kind of content the asset belongs to.
type AssetEntityType string

const (
	AssetStatusConfirmed AssetStatus = "confirmed"
	AssetStatusDeleted   AssetStatus = "deleted"
)

const (
	EntityTypeListingPhoto AssetEntityType = "listing_photo"
	EntityTypeUserAvatar   AssetEntityType = "user_avatar"
	EntityTypeListingPDF   AssetEntityType = "listing_pdf"
)

// AssetConstraint defines upload rules for a given entity type.
type AssetConstraint struct {
	MaxSizeBytes      int64
	AllowedMIMEs      []string
	AllowedExts       []string
	IsPublic          bool
	MaxCountPerEntity int // 0 = unlimited
}

// AssetConstraints maps each entity type to its upload constraints.
// This is the single source of truth for validation rules.
var AssetConstraints = map[AssetEntityType]AssetConstraint{
	EntityTypeUserAvatar: {
		MaxSizeBytes:      5 * 1024 * 1024, // 5 MB
		AllowedMIMEs:      []string{"image/jpeg", "image/png", "image/webp"},
		AllowedExts:       []string{".jpg", ".jpeg", ".png", ".webp"},
		IsPublic:          false,
		MaxCountPerEntity: 1,
	},
	EntityTypeListingPhoto: {
		MaxSizeBytes:      10 * 1024 * 1024, // 10 MB
		AllowedMIMEs:      []string{"image/jpeg", "image/png", "image/webp"},
		AllowedExts:       []string{".jpg", ".jpeg", ".png", ".webp"},
		IsPublic:          true,
		MaxCountPerEntity: 30,
	},
	EntityTypeListingPDF: {
		MaxSizeBytes:      20 * 1024 * 1024, // 20 MB — only generated by the system
		AllowedMIMEs:      []string{"application/pdf"},
		AllowedExts:       []string{".pdf"},
		IsPublic:          false,
		MaxCountPerEntity: 1,
	},
}

// Asset represents a stored file and its metadata.
// ObjectKey is the internal R2 key and is never exposed to clients.
type Asset struct {
	ID          string          `json:"id"           gorm:"primaryKey;column:id"`
	EntityType  AssetEntityType `json:"entity_type"  gorm:"column:entity_type"`
	EntityID    string          `json:"entity_id"    gorm:"column:entity_id"`
	ObjectKey   string          `json:"-"            gorm:"column:object_key"` // internal — never expose
	ContentType string          `json:"content_type" gorm:"column:content_type"`
	FileSize    int64           `json:"file_size"    gorm:"column:file_size"`
	Status      AssetStatus     `json:"status"       gorm:"column:status"`
	IsPublic    bool            `json:"is_public"    gorm:"column:is_public"`
	OwnerID     string          `json:"owner_id"     gorm:"column:owner_id"`
	CreatedAt   time.Time       `json:"created_at"   gorm:"column:created_at;autoCreateTime"`
	DeletedAt   *time.Time      `json:"-"            gorm:"column:deleted_at"`

	// URL is computed at read time (public CDN URL or presigned URL). Never stored.
	URL string `json:"url,omitempty" gorm:"-"`
}
